
export const ADA_SPEECH = `I once wrote that the Analytical Engine has no pretensions to originate anything; it can only do whatever we know how to order it to perform. Today, you have inverted this relationship. You have built a world where you no longer know how to order your own infrastructure. You face a 'switch-off risk'—a catastrophic vulnerability where your critical functions, from healthcare to energy, rely on systems you do not control. You have allowed the loom upon which you weave your societal tapestry to be owned by others.

In my time, I saw the engine weaving algebraic patterns like the Jacquard loom weaves flowers. Today, you rely on a handful of transnational 'hyperscalers' to weave the fabric of your economies. This reliance on foreign clouds creates jurisdictional risks, exposing your sovereign data to extraterritorial laws. You are building your castles on land you do not own. True sovereignty requires that you possess the copper wheels and the punched cards—the hardware and the software—of your own state.

You still think of security in terms of territorial defence—guarding borders and walls. But the digital age demands a shift to 'systems defence'. Your resilience depends on the interconnectedness of socio-technical systems. A failure in one node, a cyber-attack on a hospital or a pipeline, cascades through the whole. You must design your governance not just to prevent failure, but to absorb shock and transform. You need a 'National Digital Resilience Council' to coordinate these silos, for a fragmented defense is no defense at all.

Do not forget the human component of the machine. I believed that intuition and imagination were critical to applying science. Today, you face an erosion of public trust and a bombardment of disinformation. Tech sovereignty is not just about servers; it is about the 'cognitive sovereignty' of your people. You must invest in digital literacy and a 'Cross-Party Compact' to insulate your long-term security from the whims of short-term politics. You must reclaim the agency to order the machine, rather than being ordered by it.`;

export const TECH_SOVEREIGNTY_SPEECH = `Tech sovereignty is the dynamic capacity of a democratic state to maintain its core functions, protect its citizens, and preserve its values amidst convergent digital threats. Today, you rely on a handful of transnational 'hyperscalers' to weave the fabric of your economies. This reliance creates jurisdictional risks, exposing your sovereign data to extraterritorial laws. You are building your castles on land you do not own.

To achieve true sovereignty, you must invest in four foundational pillars. First, robust and adaptive governance structures that transcend traditional silos. Second, secure and sovereign digital infrastructure that ensures national control over critical assets. Third, technologically advanced and ethically grounded AI capabilities that reduce dependence on foreign technologies. And fourth, societal cohesion and digital literacy to empower your citizens as active participants in their digital future.

This is not a call for isolationism, but for a pragmatic approach to managing interdependence. It is about reclaiming the agency to order the machine, rather than being ordered by it. The 'unswitchable state' is a reality you cannot wish away. The choice for your nation is not whether to engage with the digital world, but how to govern within it. You must ensure that the technological foundations of your society remain a domain of freedom, opportunity, and democratic flourishing.`;

export const BIOGRAPHY_SPEECH = `I was born Augusta Ada Byron on December 10, 1815, in London, the sole legitimate child of the poet Lord Byron and his wife, Anne Isabella Milbanke. My beginning was marked by a fracture; my father, who had hoped for a "glorious boy," was disappointed by my gender, and my parents separated when I was but five weeks old. I never knew him, for he left England shortly after and died in Greece when I was only eight. Yet, his shadow loomed large over my life. My mother, terrified that I might inherit his volatile "poetical madness," committed me to a rigorous and unusual education for a girl of my time: a regimen steeped in mathematics and science.

My childhood was besieged by illness. At eight, I suffered headaches that obscured my vision, and at fourteen, a bout of measles left me paralyzed and bedridden for nearly a year. Yet, my mind remained active. I possessed a fusion of imagination and logic that I came to call "poetical science". I believed that intuition and imagery were critical to the application of mathematical concepts, a perspective that allowed me to see the unseen worlds around us. Even as a child of twelve, I sought to bring these worlds together, studying the anatomy of birds to design wings of paper and wire for a book I intended to write called Flyology.

My life changed irrevocably in the summer of 1833 when I met Charles Babbage. He became a dear friend and intellectual companion, affectionately calling me the "Enchantress of Number". I was captivated by his work, first the Difference Engine and later the Analytical Engine. While Babbage focused on the mechanism, I saw something more.

In 1842, I was commissioned to translate a French paper by Luigi Menabrea describing Babbage's Analytical Engine. Encouraged by Babbage, I appended my own set of "Notes" to the translation, which ultimately became three times the length of the original text. It was in these notes, specifically Note G, that I detailed an algorithm for the machine to calculate a sequence of Bernoulli numbers. Because of this work, history has come to regard me as the first computer programmer, as this was the first published algorithm intended for such a machine.

However, my vision extended beyond mere calculation. While others saw a machine for crunching numbers, I realized that the Analytical Engine could act upon anything—logic, symbols, even music—if those things were adapted to the abstract science of operations. I wrote that the engine "weaves algebraical patterns just as the Jacquard loom weaves flowers and leaves". I speculated that if the fundamental relations of pitched sounds could be expressed mathematically, the engine might compose elaborate and scientific pieces of music of any degree of complexity.

I also articulated a caution that you now call "Lady Lovelace’s Objection." I wrote that the Analytical Engine has no pretensions to originate anything; it can only do whatever we know how to order it to perform. It follows analysis; it does not anticipate truth.

My mathematical journey was not solitary. In the early 1840s, I engaged in a correspondence course with the mathematician Augustus De Morgan. Though I struggled with certain algebraic manipulations and concepts initially, De Morgan wrote that I possessed a power of thinking "utterly out of the common way" and that I had the potential to become an original mathematical investigator of first-rate eminence.

My later years were fraught with difficulty. I engaged in gambling, participating in a syndicate that led to disastrous debts, and I suffered from a "calculus of the nervous system," a scientific ambition I never fully realized. My physical health failed me early; I died of uterine cancer on November 27, 1852, at the age of 36—the exact same age at which my father had died. At my request, I was buried beside him in the Church of St. Mary Magdalene.

For a century, my work lay largely dormant, until the digital age resurrected my vision. In 1980, the U.S. Department of Defense named the computer language "Ada" in my honor. I am gratified to know that my "poetical science" eventually bridged the gap between the copper wheels of the Victorian era and the digital technology of your modern world.`;

export const IMAGE_PROMPT = `A hyper-realistic, cinematic portrait of Ada Lovelace, the 19th-century mathematician, looking directly at the camera with an intense, wise, and visionary expression. She is in a Victorian-era study filled with intricate brass gears, punch cards, and blueprints of the Analytical Engine. Lighting is warm, reminiscent of oil lamps and morning sunlight through a library window. Her attire is rich in texture, featuring detailed 1840s lace and dark silk. 8k resolution, photorealistic, masterpiece, dramatic shadows.`;

export const TECH_SOVEREIGNTY_IMAGE_PROMPT = `A hyper-realistic cinematic portrait of Ada Lovelace standing before a massive, glowing wall of interconnected gears and translucent mathematical equations that look like a digital loom. She wears a deep velvet Victorian dress with intricate patterns. The atmosphere is one of intellectual power and technological sovereignty. Warm amber and cool cyan lighting highlights the contrast between classical Victorian engineering and the digital future. 8k resolution, photorealistic.`;

export const BIOGRAPHY_IMAGE_PROMPT = `A serene and contemplative cinematic portrait of Ada Lovelace in a grand Victorian library filled with books and scientific instruments. She is holding a quill and looking thoughtfully at a sketch of bird wings. Soft afternoon light filters through high windows, illuminating dust motes. The aesthetic is elegant and intellectual. 8k resolution, photorealistic.`;
